openapi: 3.1.0
info:
  title: RCSB Query Proxy
  version: "1.0.0"
servers:
  - url: https://REPLACE-WITH-YOUR-RENDER-URL
paths:
  /search:
    post:
      operationId: submitRCSBQuery
      summary: Submit an RCSB-compliant structured query JSON and get matching PDB IDs
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                query:
                  type: object
                return_type:
                  type: string
                request_options:
                  type: object
              required:
                - query
                - return_type
      responses:
        "200":
          description: Matching PDB results
          content:
            application/json:
              schema:
                type: object
                properties:
                  pdb_ids:
                    type: array
                    items: {type: string}
                  download_links:
                    type: array
                    items: {type: string}
                  error:
                    type: string
