services:
  - type: web
    name: rcsb-proxy
    runtime: python
    buildCommand: ""
    startCommand: uvicorn rcsb_proxy:app --host 0.0.0.0 --port 10000
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
